# Generated by Django 2.2.6 on 2020-08-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_purchase_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isIncentive',
            field=models.BooleanField(default=False),
        ),
    ]
