# Generated by Django 2.2.6 on 2020-08-04 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_purchase_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_incentives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1: Staff with',
            },
        ),
        migrations.CreateModel(
            name='ProductIncentives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inncentive_amount', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('products', models.ManyToManyField(to='home.Product')),
            ],
            options={
                'verbose_name_plural': '2: Incentives',
            },
        ),
        migrations.CreateModel(
            name='Incentives_chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Sale')),
                ('staff_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '3: Incentives chart',
            },
        ),
    ]
